// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaa35oY71EIPb72l9bNE7mLCJ0x2I7Ftk',
    appId: '1:314407028804:web:df064b553146e0ed301411',
    messagingSenderId: '314407028804',
    projectId: 'app-store-d748a',
    authDomain: 'app-store-d748a.firebaseapp.com',
    storageBucket: 'app-store-d748a.appspot.com',
    measurementId: 'G-491M4K8X81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCirXD7V_iT_mXTzHYqXo1WZxPHja2YlH0',
    appId: '1:314407028804:android:54b2ad82ca758f5c301411',
    messagingSenderId: '314407028804',
    projectId: 'app-store-d748a',
    storageBucket: 'app-store-d748a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqHUORwk8obIsEDiyP51fll1iBQq_SEhE',
    appId: '1:314407028804:ios:303dd176bed2a75e301411',
    messagingSenderId: '314407028804',
    projectId: 'app-store-d748a',
    storageBucket: 'app-store-d748a.appspot.com',
    iosBundleId: 'com.example.appStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqHUORwk8obIsEDiyP51fll1iBQq_SEhE',
    appId: '1:314407028804:ios:4a8bf9ee159742fd301411',
    messagingSenderId: '314407028804',
    projectId: 'app-store-d748a',
    storageBucket: 'app-store-d748a.appspot.com',
    iosBundleId: 'com.example.appStore.RunnerTests',
  );
}
